spring:
  application:
    from: ${USERNAME}
    to: ${TO}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
