spring:
  application:
    from: ${UNAME}
    to: ${TO}
    cron-delay: ${CRONTIME:120}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${UNAME}
    password: ${PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  logging:
    level: INFO